name: Deploy to Cloudflare Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: pages/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./pages

      - name: Build
        run: tsc
        working-directory: ./pages

      - name: Push Cloudflare pages Branch
        run: |
          git config --local user.email "github.action@action"
          git config --local user.name "github-action"
          git add .
          git commit -m "Update"
          git push origin pages
